= io.github.rbreu.Beeref
:toc:

This is link:https://github.com/rbreu/beeref[Beeref] packaged as a Flatpak application.

WARNING: Bear in mind this is not affiliated with the developer in any way.
Take it as an unofficial way to install BeeRef in Flatpak.
In the future and if time allows, I'll discuss with the app developer how to manage distribution through Flathub (which is explicitly stated for app developers to control the distribution of their own apps).
I also just want to take a look how Flatpak are packaged.
You've been warned.




== Installation

CAUTION: Only do the following if you have an adventurous sense of installing applications.
It is recommended to install this when accepted through Flathub or something similar.

This repo should only contain the Flatpak manifest of the application.
Being a Flatpak manifest, you need Flatpak installed of course. :)
Also, you need `flatpak-builder` installed and run the following.

[source, shell]
----
flatpak-builder --user --install build/ io.github.rbreu.BeeRef.yml
----




== Setting up for development

For future contributors, you need Flatpak and `flatpak-builder` installed.

The gist of the process mostly involves following the project development and updating the dependencies.
Updating the dependencies is a bit of a pain to explain so I made sure the manifest is well-commented.
Give the link:./io.github.rbreu.BeeRef.yml[manifest] a peek, yes?

The gist of the process will usually looks like the following list:

- Follow the project.
- Look into dependencies.
- Update dependencies if there are any changes to it.
- Generate a manifest with the link:https://github.com/flatpak/flatpak-builder-tools[flatpak-builder-tools] from the dependency list (except Qt-related packages).
- Update app metadata (e.g., icons, `.desktop` file).

There are also some things to keep an eye on in my version of the manifest.

* One of the biggest blocker as of 2021-10-25 is building the PyQt bindings.
`./flatpak-builder-tools/pip/flatpak-pip-generator` cannot generate a manifest from `PyQt6` because one of the dependencies (`PyQt6-Qt6`) cannot be built from source which is the preference of Flathub overall.
`PyQt6-Qt6` contains the compiled library objects of Qt 6.

* As of 2021-10-26, the KDE runtime from Flathub is using Qt 5.
Because of that, we're compiling our own build of Qt 6.
It should be similar to link:https://pypi.org/project/PyQt6-Qt6/[PyQt6-Qt6 Pip module] which contains the compiled library objects of most Qt modules.
This project is using Qt 6 and it is important to keep an eye whether the runtime has updated to the appropriate Qt version.
So far, only the Qt base modules are required to work but it'll change as the project develops.
